import * as webllm from "https://esm.run/@mlc-ai/web-llm";
const MODEL_IDS={
 small:"SmolLM2-360M-Instruct-q4f32_1-MLC",
 balanced:"Llama-3.2-1B-Instruct-q4f16_1-MLC"
};
let engine=null,currentModel=localStorage.getItem("newai_model")||MODEL_IDS.small,chat=[];
const $=id=>document.getElementById(id),messages=$("messages"),input=$("input");
function add(role,text){$("welcome")?.remove();const row=document.createElement("div");row.className="msg "+(role==="user"?"user":"");const b=document.createElement("div");b.className="bubble";b.textContent=text;row.appendChild(b);messages.appendChild(row);messages.scrollTop=messages.scrollHeight;return b}
function setProgress(s){$("progress").textContent=s;$("state").textContent=s}
async function start(){if(engine)return;const startBtn=$("start");startBtn.disabled=true;try{setProgress("Browser-KI wird geladen …");engine=await webllm.CreateMLCEngine(currentModel,{initProgressCallback:p=>setProgress("KI wird geladen: "+Math.round((p.progress||0)*100)+"%")});setProgress("KI bereit");$("state").textContent="bereit";$("welcome")?.remove()}catch(e){setProgress("WebGPU/Modell konnte nicht geladen werden: "+e.message);$("state").textContent="nicht verfügbar";startBtn.disabled=false}}
async function send(){const t=input.value.trim();if(!t)return;if(!engine)await start();if(!engine)return;add("user",t);input.value="";chat.push({role:"user",content:t});const out=add("assistant","");try{const stream=await engine.chat.completions.create({messages:[{role:"system",content:"You are NEW AI. Be helpful, honest, concise when simple and detailed when needed. Write in the user's language. Do not claim tools or web access you did not use."},...chat],temperature:.7,max_tokens:900,stream:true});for await(const chunk of stream){out.textContent+=chunk.choices?.[0]?.delta?.content||"";messages.scrollTop=messages.scrollHeight}chat.push({role:"assistant",content:out.textContent})}catch(e){out.textContent="Fehler beim lokalen Modell: "+e.message}}
function panel(html){$("chatView").classList.add("hidden");$("panelView").classList.remove("hidden");$("panelView").innerHTML=html}
function chatView(){document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));document.querySelector('[data-view="chat"]').classList.add("active");$("panelView").classList.add("hidden");$("chatView").classList.remove("hidden")}
function modelsView(){document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));document.querySelector('[data-view="models"]').classList.add("active");panel('<h2>Modelle</h2><div class="card"><div class="model '+(currentModel===MODEL_IDS.small?"active":"")+'" id="m1"><b>SmolLM2 360M</b><div class="small">klein, geringerer Speicherbedarf</div></div><div class="model '+(currentModel===MODEL_IDS.balanced?"active":"")+'" id="m2"><b>Llama 3.2 1B</b><div class="small">größer und meist stärker, benötigt mehr Ressourcen</div></div><p class="small">Die Modelle laufen lokal im Browser via WebGPU. Beim ersten Start werden die Modell-Dateien geladen und danach gecacht. citeturn425596search2</p></div>');$("m1").onclick=()=>select(MODEL_IDS.small);$("m2").onclick=()=>select(MODEL_IDS.balanced)}
function select(m){if(engine){engine=null;chat=[];messages.innerHTML='<div class="welcome" id="welcome"><h1>Wie kann ich helfen?</h1><p>Neues Modell gewählt.</p><button id="start" class="start">KI starten</button><div id="progress" class="progress"></div></div>'; $("start").onclick=start}currentModel=m;localStorage.setItem("newai_model",m);modelsView()}
function apiView(){panel('<h2>API</h2><div class="card"><b>Discord / Server-API</b><p class="small">Der Server bleibt als optionaler OpenAI-kompatibler Gateway im Repository. Er benötigt ein echtes Modell-Backend. Die Browser-KI hier benötigt keinen API-Key.</p><p class="small">POST /v1/chat/completions · Authorization: Bearer NEWAI_KEY</p></div>')}
function aboutView(){panel('<h2>NEW AI</h2><div class="card"><p>Schlichte lokale Browser-KI.</p><p class="small">Ohne API-Key kann ein Browser ein Open-Source-Modell lokal ausführen, aber nicht automatisch dieselbe Modellgröße und Tool-Infrastruktur wie ein Cloud-Dienst bereitstellen. WebLLM nutzt WebGPU und lädt Modellgewichte in den Browser. citeturn425596search0turn755543search6</p></div>')}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{const v=b.dataset.view;if(v==="chat")chatView();if(v==="models")modelsView();if(v==="api")apiView();if(v==="about")aboutView()});
$("newChat").onclick=()=>{chat=[];messages.innerHTML='<div class="welcome" id="welcome"><h1>Wie kann ich helfen?</h1><p>Neuer Chat.</p><button id="start" class="start">KI starten</button><div id="progress" class="progress"></div></div>';$("start").onclick=start};
$("start").onclick=start;$("send").onclick=send;input.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};
$("web").onclick=()=>{window.open("https://www.google.com/search?q="+encodeURIComponent(input.value||"NEW AI"),"_blank")};
$("image").onclick=()=>add("assistant","Der Bildmodus ist vorbereitet, aber echte generative Bilder brauchen ein Bildmodell. Ohne Backend/API kann dieses Browser-Modell keine Bilddateien erzeugen.");
$("file").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{add("assistant","Datei geladen: "+f.name);chat.push({role:"user",content:"Datei: "+r.result.slice(0,50000)});};r.readAsText(f)};
