import * as webllm from "https://esm.run/@mlc-ai/web-llm";
const MODELS={small:"SmolLM2-360M-Instruct-q4f32_1-MLC",balanced:"Llama-3.2-1B-Instruct-q4f16_1-MLC"};
let engine=null,currentModel=localStorage.getItem("newai_model")||MODELS.small,chat=[];
const $=id=>document.getElementById(id),messages=$("messages"),input=$("input");
function add(role,text){$("welcome")?.remove();const row=document.createElement("div");row.className="msg "+(role==="user"?"user":"");const b=document.createElement("div");b.className="bubble";b.textContent=text;row.appendChild(b);messages.appendChild(row);messages.scrollTop=messages.scrollHeight;return b}
function progress(t){$("progress")&&( $("progress").textContent=t);$("state").textContent=t}
async function start(){if(engine)return;const btn=$("start");if(btn)btn.disabled=true;try{progress("Browser-KI wird geladen …");engine=await webllm.CreateMLCEngine(currentModel,{initProgressCallback:p=>progress("KI wird geladen: "+Math.round((p.progress||0)*100)+"%")});$("state").textContent="bereit";$("welcome")?.remove()}catch(e){progress("Modell konnte nicht geladen werden: "+e.message);if(btn)btn.disabled=false}}
async function send(){const t=input.value.trim();if(!t)return;if(!engine)await start();if(!engine)return;add("user",t);input.value="";chat.push({role:"user",content:t});const out=add("assistant","");try{const stream=await engine.chat.completions.create({messages:[{role:"system",content:"You are NEW AI. Be helpful, accurate and honest. Answer in the user's language. Do not claim web access or tools you did not use."},...chat],temperature:.7,max_tokens:900,stream:true});for await(const chunk of stream){out.textContent+=chunk.choices?.[0]?.delta?.content||"";messages.scrollTop=messages.scrollHeight}chat.push({role:"assistant",content:out.textContent})}catch(e){out.textContent="Fehler beim lokalen Modell: "+e.message}}
function showChat(){document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));document.querySelector('[data-view="chat"]').classList.add("active");$("panelView").classList.add("hidden");$("chatView").classList.remove("hidden")}
function panel(html){$("chatView").classList.add("hidden");$("panelView").classList.remove("hidden");$("panelView").innerHTML=html}
function modelsView(){document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));document.querySelector('[data-view="models"]').classList.add("active");panel('<h2>Modelle</h2><div class="card"><div class="model '+(currentModel===MODELS.small?"active":"")+'" id="m1"><b>SmolLM2 360M</b><div class="small">kleines Modell für schwächere Geräte</div></div><div class="model '+(currentModel===MODELS.balanced?"active":"")+'" id="m2"><b>Llama 3.2 1B</b><div class="small">größer und meist stärker, braucht mehr Ressourcen</div></div><p class="small">Die Modelle werden direkt im Browser geladen und lokal ausgeführt.</p></div>');$("m1").onclick=()=>select(MODELS.small);$("m2").onclick=()=>select(MODELS.balanced)}
function select(m){currentModel=m;localStorage.setItem("newai_model",m);engine=null;chat=[];modelsView()}
function apiView(){panel('<h2>API</h2><div class="card"><b>Optionaler API-Gateway</b><p class="small">Das Repository enthält zusätzlich einen OpenAI-kompatiblen Server für Discord-Bots. Die Browser-KI selbst benötigt keinen API-Key.</p><p class="small">POST /v1/chat/completions mit Authorization: Bearer NEWAI_KEY</p></div>')}
function aboutView(){panel('<h2>System</h2><div class="card"><p>NEW AI läuft lokal im Browser. Ein echtes Cloud-Modell in ChatGPT-Größe, Cloud-Bildgenerierung oder ein öffentlicher Discord-API-Dienst kann nicht allein aus statischem GitHub-Code entstehen.</p><p class="small">Ohne Backend/API bleiben die generativen Fähigkeiten auf das lokal geladene Modell und lokale Browser-Werkzeuge begrenzt.</p></div>')}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{const v=b.dataset.view;if(v==="chat")showChat();if(v==="models")modelsView();if(v==="api")apiView();if(v==="about")aboutView()});
$("newChat").onclick=()=>{chat=[];messages.innerHTML='<div class="welcome" id="welcome"><h1>Wie kann ich helfen?</h1><p>Neuer Chat.</p><button id="start" class="start">KI starten</button><div id="progress" class="progress"></div></div>';$("start").onclick=start};
$("start").onclick=start;$("send").onclick=send;input.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};
$("web").onclick=()=>window.open("https://www.google.com/search?q="+encodeURIComponent(input.value||"NEW AI"),"_blank");
$("image").onclick=()=>add("assistant","Echte KI-Bildgenerierung braucht ein Bildmodell; dieses lokale Textmodell erzeugt keine Bilddateien.");
$("file").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{add("assistant","Datei geladen: "+f.name);chat.push({role:"user",content:"Dateiinhalt:\n"+String(r.result).slice(0,50000)});};r.readAsText(f)};