const s=localStorage;
const st={base:s.getItem("newai_base")||"",key:s.getItem("newai_key")||"",model:s.getItem("newai_model")||"new-ai",web:false,image:false,messages:[],file:""};
const $=x=>document.getElementById(x), messages=$("messages"), input=$("input");
function save(){s.setItem("newai_base",st.base);s.setItem("newai_key",st.key);s.setItem("newai_model",st.model)}
function esc(x){return String(x).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function add(role,text,sources=[]){$("welcome")?.remove();const row=document.createElement("div");row.className="msg "+(role==="user"?"user":"");const b=document.createElement("div");b.className="bubble";b.textContent=text;row.appendChild(b);messages.appendChild(row);if(sources.length){const box=document.createElement("div");box.className="sources";sources.forEach(x=>{const a=document.createElement("a");a.href=x.url;a.target="_blank";a.rel="noopener";a.textContent=x.title||x.url;box.appendChild(a)});messages.appendChild(box)}messages.scrollTop=messages.scrollHeight}
function endpoint(path){return st.base.replace(/\/$/,"")+path}
async function health(){if(!st.base){$("state").textContent="nicht verbunden";return}try{const r=await fetch(endpoint("/health"));$("state").textContent=r.ok?"verbunden":"fehler"}catch{$("state").textContent="nicht erreichbar"}}
async function send(){const raw=input.value.trim();if(!raw)return;if(st.image){await image(raw);return}let content=st.file?"[Datei-Inhalt]\n"+st.file+"\n\n"+raw:raw;add("user",raw);input.value="";st.messages.push({role:"user",content});const wait="…";const row=document.createElement("div");row.className="msg";row.innerHTML="<div class='bubble'>"+wait+"</div>";messages.appendChild(row);messages.scrollTop=messages.scrollHeight;try{if(!st.base)throw new Error("Backend nicht konfiguriert");const r=await fetch(endpoint("/v1/chat/completions"),{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+st.key},body:JSON.stringify({model:st.model,messages:st.messages,web_search:st.web})});const data=await r.json();if(!r.ok)throw new Error(data.detail||"API error");row.remove();add("assistant",data.choices?.[0]?.message?.content||"Keine Antwort.",data.sources||[]);st.messages.push({role:"assistant",content:data.choices?.[0]?.message?.content||""});}catch(e){row.querySelector(".bubble").textContent="Verbindung fehlgeschlagen: "+e.message}}
async function image(prompt){add("user","Bild: "+prompt);st.image=false;$("image").classList.remove("active");if(!st.base||!st.key){add("assistant","Bildgenerierung braucht einen konfigurierten Bild-Provider.");return}try{const r=await fetch(endpoint("/v1/images/generations"),{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+st.key},body:JSON.stringify({prompt,size:"1024x1024",n:1})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Image API error");const url=d.data?.[0]?.url||d.data?.[0]?.b64_json;add("assistant",url?"Bild erstellt.\n"+url:"Provider hat kein Bild zurückgegeben.");}catch(e){add("assistant","Bildfehler: "+e.message)}}
function showPanel(html){$("chatView").classList.add("hidden");$("panelView").classList.remove("hidden");$("panelView").innerHTML=html}
function showChat(){ $("panelView").classList.add("hidden");$("chatView").classList.remove("hidden"); document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));document.querySelector('[data-view="chat"]').classList.add("active")}
function showSettings(){document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));document.querySelector('[data-view="settings"]').classList.add("active");showPanel('<h2>Verbindung</h2><div class="card"><div>Backend URL</div><input class="field" id="base" placeholder="https://dein-server.example.com"><div>NEW AI API-Key</div><input class="field" id="key" placeholder="newai_…"><div>Model</div><input class="field" id="model" value="'+esc(st.model)+'"><button class="save" id="save">Speichern & testen</button><p class="small">Der Key bleibt in diesem Browser gespeichert. Provider-Keys gehören niemals in GitHub oder ins Frontend.</p></div>');$("base").value=st.base;$("key").value=st.key;$("save").onclick=()=>{st.base=$("base").value.trim();st.key=$("key").value.trim();st.model=$("model").value.trim()||"new-ai";save();health();alert("Gespeichert.")}}
function showApi(){showPanel('<h2>API</h2><div class="card"><b>OpenAI-kompatibel</b><p class="small">POST /v1/chat/completions · Header Authorization: Bearer NEWAI_KEY</p><p class="small">Für Discord-Bots zeigt <code>discord_bot.py</code> den Aufruf. Server-seitige Provider-Keys werden nie an Discord ausgeliefert.</p></div><div class="card"><b>Admin</b><p class="small">API-Keys erzeugst du über POST /admin/keys mit x-admin-key. Der Server speichert nur Hashes.</p></div>')}
function showAbout(){showPanel('<h2>NEW AI</h2><div class="card"><p>Schlichte Oberfläche, echter Backend-Core.</p><p class="small">Das Modell selbst kommt aus deinem konfigurierten lokalen oder OpenAI-kompatiblen Backend. NEW AI kann keine fremden Modellgewichte oder privaten Trainingsdaten übernehmen.</p></div>')}
document.querySelectorAll(".nav").forEach(b=>b.onclick=e=>{const v=b.dataset.view;if(v==="chat")showChat();if(v==="settings")showSettings();if(v==="api")showApi();if(v==="about")showAbout()});
$("newChat").onclick=()=>{st.messages=[];messages.innerHTML='<div class="welcome" id="welcome"><h1>Wie kann ich helfen?</h1><p>Neuer Chat.</p></div>';input.focus()}
$("web").onclick=()=>{st.web=!st.web;$("web").classList.toggle("active",st.web)}
$("image").onclick=()=>{st.image=!st.image;$("image").classList.toggle("active",st.image);input.placeholder=st.image?"Bildbeschreibung …":"Nachricht …"}
$("file").onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{st.file=rd.result.slice(0,200000);add("assistant","Datei geladen: "+f.name)};rd.readAsText(f)}
$("send").onclick=send;input.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};health();
