const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const apps={KI:["✦","KI","Der visuelle KI-Bereich von NEW SYSTEM."],Fotos:["▧","Fotos","Alben, Bilder und Medien – in einem echten Android-Build über erlaubte Medien-APIs."],Dateien:["▤","Dateien","Dateimanager für Speicher, Ordner und Downloads."],Musik:["♫","Musik","Musikplayer mit Wiedergabe und Bibliothek."],Browser:["◎","Browser","Webzugang innerhalb des System-Prototyps."],Telefon:["☎","Telefon","Telefon-Oberfläche und Kontakte."],Nachrichten:["▣","Nachrichten","Nachrichten und Chats."],Kamera:["◉","Kamera","Kamera-Oberfläche für einen späteren Android-Build."],Einstellungen:["⚙","Einstellungen","Systemeinstellungen, Berechtigungen und Geräteoptionen."]};
function clock(){const d=new Date(),t=d.toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"});["#time","#sysTime"].forEach(x=>{const e=$(x);if(e)e.textContent=t})}setInterval(clock,1000);clock();
function openApp(name){const a=apps[name]||["✦",name,"NEW SYSTEM"];$("#modalIcon").textContent=a[0];$("#modalTitle").textContent=a[1];$("#modalText").textContent=a[2];$("#modalList").innerHTML=["Übersicht","Letzte Elemente","Optionen","Berechtigungen"].map(x=>"<div>› "+x+"</div>").join("");$("#modal").classList.add("open")}
$$("[data-app]").forEach(b=>b.addEventListener("click",()=>openApp(b.dataset.app)));
$("#close").onclick=()=>$("#modal").classList.remove("open");$("#modal").addEventListener("click",e=>{if(e.target.id==="modal")$("#modal").classList.remove("open")});
$$("[data-toggle]").forEach(b=>b.onclick=()=>{b.classList.toggle("active");b.querySelector("span").textContent=b.classList.contains("active")?"Aktiv":"Aus"});
function build(){const term=$("#terminal"),state=$("#buildState"),lines=["› Build gestartet …","› Systemkern-Oberfläche wird vorbereitet …","› Startbildschirm erstellt.","› Schnelleinstellungen erstellt.","› Apps registriert.","› Dateien / Fotos / Musik vorbereitet.","› Deutsche Systemtexte geladen.","› Start-Animation eingebunden.","› Prüfung: Demo bereit.","✓ NEW SYSTEM wurde gebaut."];term.innerHTML="";state.textContent="BAUT …";lines.forEach((line,i)=>setTimeout(()=>{term.innerHTML+="<p>"+line+"</p>";term.scrollTop=term.scrollHeight;if(i===lines.length-1)state.textContent="FERTIG"},i*240))}
$("#build").onclick=()=>{build();location.hash="builder"};$("#build2").onclick=build;$("#launch").onclick=()=>{document.querySelector("#boot").classList.remove("hide");setTimeout(()=>document.querySelector("#boot").classList.add("hide"),1400)};
setTimeout(()=>$("#boot").classList.add("hide"),1800);