const $=id=>document.getElementById(id);let file=null,buffer=null,resultUrl=null,audioCtx=null;
const presets={clean:{gain:0,bass:0,treble:0,comp:25,reverb:5,echo:0,speed:100,pitch:0},loud:{gain:6,bass:5,treble:2,comp:72,reverb:6,echo:2,speed:100,pitch:0},bass:{gain:4,bass:12,treble:1,comp:62,reverb:8,echo:3,speed:100,pitch:0},tiktok:{gain:5,bass:7,treble:3,comp:82,reverb:8,echo:1,speed:104,pitch:.5},club:{gain:5,bass:9,treble:2,comp:78,reverb:22,echo:10,speed:100,pitch:0}};
function set(id,v){$(id).value=v;$(id+"Out").textContent=fmt(id,v)}
function fmt(id,v){if(id==="gain")return (v>=0?"+":"")+Number(v).toFixed(1)+" dB";if(["bass","treble"].includes(id))return (v>=0?"+":"")+v+" dB";if(["comp","reverb","echo","speed"].includes(id))return v+"%";if(id==="pitch")return (v>0?"+":"")+v;return Number(v).toFixed(1)+" s"}
function refresh(){["start","end","gain","bass","treble","comp","reverb","echo","speed","pitch"].forEach(id=>$(id+"Out").textContent=fmt(id,$(id).value))}
document.querySelectorAll(".presets button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".presets button").forEach(x=>x.classList.remove("active"));b.classList.add("active");const p=presets[b.dataset.p];if(!p)return;Object.entries(p).forEach(([k,v])=>set(k,v));refresh()});
$("file").onchange=e=>loadFile(e.target.files[0]);$("drop").onclick=()=>$("file").click();["dragover","drop"].forEach(ev=>$("drop").addEventListener(ev,e=>e.preventDefault()));$("drop").addEventListener("drop",e=>loadFile(e.dataTransfer.files[0]));
async function loadFile(f){if(!f)return;if(!f.type.startsWith("audio/"))return;file=f;const url=URL.createObjectURL(f);$("preview").src=url;$("name").textContent=f.name;$("fileCard").hidden=false;$("status").textContent="Audio wird analysiert …";audioCtx=audioCtx||new AudioContext();const ab=await f.arrayBuffer();buffer=await audioCtx.decodeAudioData(ab.slice(0));const dur=buffer.duration;["start","end"].forEach((id,i)=>{const el=$(id);el.max=dur;el.value=i?dur:0});$("endOut").textContent=fmt("end",dur);$("startOut").textContent="0.0 s";drawWave();$("status").textContent="Bereit · "+dur.toFixed(2)+" s · "+buffer.numberOfChannels+" Kanal(e)";$("aiState").textContent="Audio erkannt. Wähle ein Preset oder stelle alles selbst ein."}
function drawWave(){const c=$("wave"),ctx=c.getContext("2d"),w=c.clientWidth*2,h=c.clientHeight*2;c.width=w;c.height=h;ctx.clearRect(0,0,w,h);const ch=buffer.getChannelData(0),step=Math.max(1,Math.floor(ch.length/w));ctx.beginPath();for(let x=0;x<w;x++){let min=1,max=-1;for(let j=0;j<step;j++){const v=ch[x*step+j]||0;min=Math.min(min,v);max=Math.max(max,v)}ctx.moveTo(x,h/2+min*h*.38);ctx.lineTo(x,h/2+max*h*.38)}ctx.strokeStyle="#777";ctx.stroke()}
$("play").onclick=()=>{$("preview").play()};
$("render").onclick=render;
async function render(){if(!buffer){$("status").textContent="Erst eine Audiodatei laden.";return}let start=+$("start").value,end=+$("end").value;if(end<=start+.05){$("status").textContent="Ende muss hinter dem Start liegen.";return}const speed=+$("speed").value/100;const dur=(end-start)/speed;const rate=buffer.sampleRate,outLen=Math.ceil(dur*rate),offline=new OfflineAudioContext(2,outLen,rate);
const src=offline.createBufferSource();src.buffer=buffer;src.playbackRate.value=speed;src.connect(offline.destination);src.start(0,start,end);
const rendered=await offline.startRendering();const final=process(rendered);const wav=toWav(final);if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=URL.createObjectURL(wav);$("resultAudio").src=resultUrl;$("download").href=resultUrl;$("resultMeta").textContent=final.duration.toFixed(2)+" s · WAV · "+final.numberOfChannels+" Kanal(e)";$("output").hidden=false;$("status").textContent="Remix fertig.";ask()}
function process(src){const gain=Math.pow(10,+$("gain").value/20),bass=+$("bass").value,treble=+$("treble").value,comp=+$("comp").value/100,rev=+$("reverb").value/100,echo=+$("echo").value/100,cut=$("cutQuiet").checked,guard=$("clipGuard").checked,stereo=$("stereo").checked,out=new OfflineAudioContext(2,src.length,src.sampleRate),bs=out.createBufferSource();bs.buffer=src;
const g=out.createGain();g.gain.value=gain;const low=out.createBiquadFilter();low.type="lowshelf";low.frequency.value=140;low.gain.value=bass;const high=out.createBiquadFilter();high.type="highshelf";high.frequency.value=4200;high.gain.value=treble;const c=out.createDynamicsCompressor();c.threshold.value=-28+24*(1-comp);c.ratio.value=1+11*comp;c.attack.value=.004;c.release.value=.12;
bs.connect(low).connect(high).connect(c).connect(g).connect(out.destination);
if(echo>0){const d=out.createDelay(1);d.delayTime.value=.22;const eg=out.createGain();eg.gain.value=.18*echo;bs.connect(d).connect(eg).connect(out.destination)}
if(rev>0){const conv=out.createConvolver(),rv=out.createBuffer(2,Math.floor(out.sampleRate*1.2),out.sampleRate);for(let ch=0;ch<2;ch++){const a=rv.getChannelData(ch);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/a.length,2.2)}conv.buffer=rv;const rg=out.createGain();rg.gain.value=.25*rev;bs.connect(conv).connect(rg).connect(out.destination)}
bs.start();return out};
async function normalize(b){return b}
function toWav(b){let n=b.length,channels=Math.min(2,b.numberOfChannels),buf=new ArrayBuffer(44+n*channels*2),v=new DataView(buf);write(v,0,"RIFF");v.setUint32(4,36+n*channels*2,true);write(v,8,"WAVE");write(v,12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,channels,true);v.setUint32(24,b.sampleRate,true);v.setUint32(28,b.sampleRate*channels*2,true);v.setUint16(32,channels*2,true);v.setUint16(34,16,true);write(v,36,"data");v.setUint32(40,n*channels*2,true);let o=44,max=+$("clipGuard").checked?.98:1;for(let i=0;i<n;i++){for(let ch=0;ch<channels;ch++){let x=b.getChannelData(ch)[i]*max;x=Math.max(-1,Math.min(1,x));v.setInt16(o,x<0?x*32768:x*32767,true);o+=2}}return new Blob([v],{type:"audio/wav"})}
function write(v,o,s){for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))}
function ask(){const loud=+$("gain").value>=5, bass=+$("bass").value>=8, comp=+$("comp").value>=70;let q=loud&&bass?"Laut und bassig. Ist der Druck gut oder soll ich noch cleaner werden?":comp?"Schon stark komprimiert. Soll es noch härter oder natürlicher werden?":"Wie klingt der erste Remix? Gut, besser oder ganz anders?";$("question").textContent=q;$("ask").hidden=false;$("aiState").textContent="Remix analysiert · bereit für Feintuning."}
document.querySelectorAll(".answers button").forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==="gut"){$("aiState").textContent="Gespeichert. Diese Mischung gefällt dir.";return}if(a==="besser"){$("gain").value=Math.min(12,+$("gain").value+1);$("comp").value=Math.min(100,+$("comp").value+8);$("bass").value=Math.min(18,+$("bass").value+2);refresh();$("aiState").textContent="Ich habe mehr Druck, Lautheit und Kontrolle eingestellt. Rendere nochmal."}else{$("reverb").value=Math.max(0,+$("reverb").value-7);$("treble").value=Math.min(10,+$("treble").value+2);$("echo").value=Math.max(0,+$("echo").value-3);refresh();$("aiState").textContent="Ich habe es cleaner und direkter gemacht. Rendere nochmal."}});
$("reset").onclick=()=>location.reload();refresh();