const $=id=>document.getElementById(id);let file=null,buffer=null,resultUrl=null,audioCtx=null;
const presets={clean:{gain:0,bass:0,treble:0,comp:25,reverb:5,echo:0,speed:100,pitch:0},loud:{gain:6,bass:5,treble:2,comp:72,reverb:6,echo:2,speed:100,pitch:0},bass:{gain:4,bass:12,treble:1,comp:62,reverb:8,echo:3,speed:100,pitch:0},tiktok:{gain:5,bass:7,treble:3,comp:82,reverb:8,echo:1,speed:104,pitch:.5},club:{gain:5,bass:9,treble:2,comp:78,reverb:22,echo:10,speed:100,pitch:0}};
function setv(id,v){$(id).value=v;$(id+"Out").textContent=fmt(id,v)}function fmt(id,v){v=Number(v);if(id==="gain")return(v>=0?"+":"")+v.toFixed(1)+" dB";if(["bass","treble"].includes(id))return(v>=0?"+":"")+v+" dB";if(["comp","reverb","echo","speed"].includes(id))return v+"%";if(id==="pitch")return(v>0?"+":"")+v+" st";return v.toFixed(1)+" s"}function refresh(){["start","end","gain","bass","treble","comp","reverb","echo","speed","pitch"].forEach(id=>$(id+"Out").textContent=fmt(id,$(id).value))}
document.querySelectorAll(".presets button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".presets button").forEach(x=>x.classList.remove("active"));b.classList.add("active");const p=presets[b.dataset.p];if(p)Object.entries(p).forEach(([k,v])=>setv(k,v))});
$("file").onchange=e=>loadFile(e.target.files[0]);$("drop").onclick=()=>$("file").click();$("drop").ondragover=e=>e.preventDefault();$("drop").ondrop=e=>{e.preventDefault();loadFile(e.dataTransfer.files[0])};
async function loadFile(f){if(!f||!f.type.startsWith("audio/"))return;file=f;const url=URL.createObjectURL(f);$("preview").src=url;$("name").textContent=f.name;$("fileCard").hidden=false;audioCtx=audioCtx||new AudioContext();$("status").textContent="Audio wird analysiert …";const ab=await f.arrayBuffer();buffer=await audioCtx.decodeAudioData(ab.slice(0));const dur=buffer.duration;["start","end"].forEach((id,i)=>{const el=$(id);el.max=dur;el.value=i?dur:0});$("endOut").textContent=fmt("end",dur);drawWave();$("status").textContent="Bereit · "+dur.toFixed(2)+" s · "+buffer.numberOfChannels+" Kanal(e)";$("aiState").textContent="Audio erkannt. Wähle Preset oder stelle alles selbst ein."}
function drawWave(){const c=$("wave"),ctx=c.getContext("2d"),w=Math.max(600,c.clientWidth*2),h=Math.max(140,c.clientHeight*2);c.width=w;c.height=h;ctx.clearRect(0,0,w,h);const ch=buffer.getChannelData(0),step=Math.max(1,Math.floor(ch.length/w));ctx.beginPath();for(let x=0;x<w;x++){let mn=1,mx=-1;for(let j=0;j<step;j++){const v=ch[x*step+j]||0;mn=Math.min(mn,v);mx=Math.max(mx,v)}ctx.moveTo(x,h/2+mn*h*.38);ctx.lineTo(x,h/2+mx*h*.38)}ctx.strokeStyle="#777";ctx.stroke()}
$("play").onclick=()=>$("preview").play();$("render").onclick=render;
async function render(){if(!buffer){$("status").textContent="Erst Audio laden.";return}let start=+$("start").value,end=+$("end").value;if(end<=start+.05){$("status").textContent="Ende muss hinter Start liegen.";return}const speed=+$("speed").value/100,pitch=+$("pitch").value,rate=buffer.sampleRate;const effectiveRate=speed*Math.pow(2,pitch/12);const duration=(end-start)/effectiveRate;const total=Math.ceil((duration+.8)*rate),offline=new OfflineAudioContext(2,total,rate),src=offline.createBufferSource();src.buffer=buffer;src.playbackRate.value=effectiveRate;if("detune" in src)src.detune.value=0;
const gain=offline.createGain();gain.gain.value=Math.pow(10,+$("gain").value/20);const low=offline.createBiquadFilter();low.type="lowshelf";low.frequency.value=140;low.gain.value=+$("bass").value;const high=offline.createBiquadFilter();high.type="highshelf";high.frequency.value=4200;high.gain.value=+$("treble").value;const comp=offline.createDynamicsCompressor();const cr=+$("comp").value/100;comp.threshold.value=-30+22*(1-cr);comp.ratio.value=1+13*cr;comp.knee.value=8;comp.attack.value=.003;comp.release.value=.12;
src.connect(low).connect(high).connect(comp).connect(gain).connect(offline.destination);
const echo=+$("echo").value/100;if(echo){const d=offline.createDelay(1),eg=offline.createGain();d.delayTime.value=.18;eg.gain.value=.22*echo;src.connect(d).connect(eg).connect(offline.destination)}
const rev=+$("reverb").value/100;if(rev){const conv=offline.createConvolver(),rv=offline.createBuffer(2,Math.floor(rate*.9),rate);for(let ch=0;ch<2;ch++){const a=rv.getChannelData(ch);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/a.length,2.8)}conv.buffer=rv;const rg=offline.createGain();rg.gain.value=.22*rev;src.connect(conv).connect(rg).connect(offline.destination)}
$("render").disabled=true;$("status").textContent="Remix wird gerendert …";src.start(0,start,end);const rendered=await offline.startRendering();const final=postProcess(rendered);const wav=toWav(final);if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=URL.createObjectURL(wav);$("resultAudio").src=resultUrl;$("download").href=resultUrl;$("output").hidden=false;$("resultMeta").textContent=final.duration.toFixed(2)+" s · WAV · "+final.numberOfChannels+" Kanal(e)";$("status").textContent="Remix fertig.";$("render").disabled=false;ask()}
function postProcess(b){const out=audioCtx.createBuffer(2,b.length,b.sampleRate),width=$("stereo").checked?.18:0,cut=$("cutQuiet").checked;for(let i=0;i<b.length;i++){let l=b.numberOfChannels>0?b.getChannelData(0)[i]:0,r=b.numberOfChannels>1?b.getChannelData(1)[i]:l,mid=(l+r)/2,side=(l-r)/2;let amp=Math.max(Math.abs(l),Math.abs(r));if(cut&&amp<.012){l*=.18;r*=.18}if(width){l=mid+side*(1+width);r=mid-side*(1+width)}const lim=.985;l=Math.max(-lim,Math.min(lim,l));r=Math.max(-lim,Math.min(lim,r));out.getChannelData(0)[i]=l;out.getChannelData(1)[i]=r}return out}
function toWav(b){const n=b.length,ch=2,buf=new ArrayBuffer(44+n*ch*2),v=new DataView(buf);write(v,0,"RIFF");v.setUint32(4,36+n*ch*2,true);write(v,8,"WAVE");write(v,12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,b.sampleRate,true);v.setUint32(28,b.sampleRate*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);write(v,36,"data");v.setUint32(40,n*ch*2,true);let o=44;for(let i=0;i<n;i++)for(let c=0;c<ch;c++){let x=b.getChannelData(c)[i];v.setInt16(o,x<0?x*32768:x*32767,true);o+=2}return new Blob([v],{type:"audio/wav"})}function write(v,o,s){for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))}
function ask(){const loud=+$("gain").value>=5,bass=+$("bass").value>=8,comp=+$("comp").value>=70;let q=loud&&bass?"Laut und bassig. Ist der Druck gut oder soll ich es noch cleaner machen?":comp?"Stark komprimiert. Soll es härter oder natürlicher werden?":"Wie klingt der Remix? Gut, besser oder ganz anders?";$("question").textContent=q;$("ask").hidden=false;$("aiState").textContent="Mix analysiert · bereit für Feintuning."}
document.querySelectorAll(".answers button").forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==="gut"){$("aiState").textContent="Okay. Diese Mischung ist als Version gespeichert.";return}if(a==="besser"){$("gain").value=Math.min(12,+$("gain").value+1);$("comp").value=Math.min(100,+$("comp").value+8);$("bass").value=Math.min(18,+$("bass").value+2);refresh();$("aiState").textContent="Mehr Druck, Lautheit und Kontrolle eingestellt. Nochmal rendern."}else{$("reverb").value=Math.max(0,+$("reverb").value-7);$("treble").value=Math.min(10,+$("treble").value+2);$("echo").value=Math.max(0,+$("echo").value-3);refresh();$("aiState").textContent="Cleaner und direkter eingestellt. Nochmal rendern."}});
$("reset").onclick=()=>location.reload();refresh();